#!/opt/homebrew/bin/python3.11
"""
Export all reviewed portfolio data as a single idempotent SQL file for
production (Railway Postgres).

Semantics (single-user app → full mirror):
  - The user row itself is upserted so the user_id exists in prod.
  - Per-user tables: DELETE the user's rows, then INSERT local state.
  - Shared tables (catalogs, rates, price history): DELETE ALL + INSERT with
    original ids — deterministic and idempotent (several catalogs have no
    unique constraint, so ON CONFLICT can't be trusted to dedup).
  - Serial sequences are bumped past max(id) at the end.

Usage:
    cd backend
    python scripts/export_user_data.py --user user_59ae3aa75f1ef4ed > prod_sync.sql
    # then apply to Railway:
    #   railway connect postgres   (or: psql $PROD_DATABASE_URL -f prod_sync.sql)

Flags:
    --skip-prices    omit stock_price_history (largest table; prod will lazily
                     refetch from yfinance instead)
"""
import argparse
import logging
import sys
from pathlib import Path

# Engine logging would leak INFO lines into the SQL on stdout
logging.disable(logging.CRITICAL)

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

import json                                      # noqa: E402
from decimal import Decimal                      # noqa: E402
from sqlalchemy import text                      # noqa: E402
from app.core.database import engine             # noqa: E402


# (table, user_scoped, conflict_clause_for_shared)
USER_TABLES = [
    "israeli_stock_transactions",
    "israeli_stock_holdings",
    "israeli_dividends",
    "israeli_report_uploads",
    "pending_israeli_transactions",
    "world_stock_transactions",
    "world_stock_holdings",
    "world_dividends",
    "pending_world_transactions",
]

SHARED_TABLES = [
    "israeli_stocks",
    "world_stocks",
    "exchange_rates",
    "stock_prices",
    "stock_earnings_dates",
    "stock_price_history",
]


def sql_literal(v) -> str:
    """Explicit escaping: psycopg2's adapt() needs a connection encoding and
    breaks on Hebrew company names, so quote manually. Postgres runs with
    standard_conforming_strings=on, so only single quotes need doubling."""
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "TRUE" if v else "FALSE"
    if isinstance(v, (int, float, Decimal)):
        return str(v)
    if isinstance(v, dict):                  # JSON columns (e.g. raw_data)
        s = json.dumps(v, ensure_ascii=False)
    elif isinstance(v, list):                # Postgres ARRAY columns (e.g. indices)
        inner = ",".join(
            '"' + str(x).replace("\\", "\\\\").replace('"', '\\"') + '"' for x in v
        )
        s = "{" + inner + "}"
    else:
        s = str(v)                            # str, date, datetime, UUID
    return "'" + s.replace("'", "''") + "'"


def columns_of(conn, table: str) -> list[str]:
    rows = conn.execute(text("""
        SELECT column_name FROM information_schema.columns
        WHERE table_name = :t AND table_schema = 'public'
        ORDER BY ordinal_position
    """), {"t": table}).fetchall()
    return [r[0] for r in rows]


def dump_rows(conn, table: str, cols: list[str], where: str = "", params: dict = {},
              conflict: str = "", exclude_id: bool = False) -> list[str]:
    use_cols = [c for c in cols if not (exclude_id and c == "id")]
    col_list = ", ".join(use_cols)
    rows = conn.execute(
        text(f'SELECT {col_list} FROM "{table}" {where}'), params
    ).fetchall()
    out = []
    for r in rows:
        vals = ", ".join(sql_literal(v) for v in r)
        out.append(f'INSERT INTO "{table}" ({col_list}) VALUES ({vals}) {conflict};')
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--user", required=True)
    ap.add_argument("--skip-prices", action="store_true")
    args = ap.parse_args()

    lines = [
        "-- Investracker production sync (generated by scripts/export_user_data.py)",
        f"-- user: {args.user}",
        "BEGIN;",
        "",
    ]

    all_tables: list[str] = []
    with engine.connect() as conn:
        # The user row itself (id must exist before user-scoped inserts)
        ucols = columns_of(conn, "users")
        urows = dump_rows(conn, "users", ucols,
                          where="WHERE id = :u", params={"u": args.user},
                          conflict="ON CONFLICT (id) DO NOTHING")
        lines.append(f"-- users: {len(urows)} rows")
        lines.extend(urows)
        lines.append("")

        # Shared tables: full mirror (delete all + insert with original ids)
        for table in SHARED_TABLES:
            if args.skip_prices and table == "stock_price_history":
                continue
            cols = columns_of(conn, table)
            lines.append(f'DELETE FROM "{table}";')
            rows = dump_rows(conn, table, cols)
            lines.append(f"-- {table}: {len(rows)} rows")
            lines.extend(rows)
            lines.append("")
            all_tables.append(table)

        for table in USER_TABLES:
            cols = columns_of(conn, table)
            lines.append(f'DELETE FROM "{table}" WHERE user_id = {sql_literal(args.user)};')
            rows = dump_rows(conn, table, cols,
                             where="WHERE user_id = :u", params={"u": args.user})
            lines.append(f"-- {table}: {len(rows)} rows")
            lines.extend(rows)
            lines.append("")
            all_tables.append(table)

    # Bump serial sequences past the inserted ids
    lines.append("-- fix sequences")
    for table in all_tables:
        lines.append(
            f"SELECT setval(pg_get_serial_sequence('{table}', 'id'), "
            f"COALESCE((SELECT MAX(id) FROM \"{table}\"), 1));"
        )
    lines.append("COMMIT;")
    print("\n".join(lines))
    print(f"-- done: {len(lines)} statements", file=sys.stderr)


if __name__ == "__main__":
    main()
