"""add_user_role_column

Revision ID: 2d0c4f7eb166
Revises: 2025_11_08_1900
Create Date: 2025-12-05 16:43:58.208099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d0c4f7eb166'
down_revision = '2025_11_08_1900'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('WorldStockAccount_account_number_key', 'WorldStockAccount', type_='unique')
    op.drop_index('idx_world_account_number', table_name='WorldStockAccount')
    op.drop_index('idx_world_account_user_id', table_name='WorldStockAccount')
    op.create_index(op.f('ix_WorldStockAccount_account_number'), 'WorldStockAccount', ['account_number'], unique=True)
    op.create_index(op.f('ix_WorldStockAccount_id'), 'WorldStockAccount', ['id'], unique=False)
    op.create_index(op.f('ix_WorldStockAccount_user_id'), 'WorldStockAccount', ['user_id'], unique=False)
    op.drop_index('idx_world_dividend_account_id', table_name='WorldStockDividend')
    op.drop_index('idx_world_dividend_date', table_name='WorldStockDividend')
    op.drop_index('idx_world_dividend_symbol', table_name='WorldStockDividend')
    op.drop_index('idx_world_dividend_user_id', table_name='WorldStockDividend')
    op.create_index(op.f('ix_WorldStockDividend_account_id'), 'WorldStockDividend', ['account_id'], unique=False)
    op.create_index(op.f('ix_WorldStockDividend_id'), 'WorldStockDividend', ['id'], unique=False)
    op.create_index(op.f('ix_WorldStockDividend_payment_date'), 'WorldStockDividend', ['payment_date'], unique=False)
    op.create_index(op.f('ix_WorldStockDividend_symbol'), 'WorldStockDividend', ['symbol'], unique=False)
    op.create_index(op.f('ix_WorldStockDividend_user_id'), 'WorldStockDividend', ['user_id'], unique=False)
    op.drop_index('idx_world_holding_account_id', table_name='WorldStockHolding')
    op.drop_index('idx_world_holding_symbol', table_name='WorldStockHolding')
    op.drop_index('idx_world_holding_user_id', table_name='WorldStockHolding')
    op.create_index(op.f('ix_WorldStockHolding_account_id'), 'WorldStockHolding', ['account_id'], unique=False)
    op.create_index(op.f('ix_WorldStockHolding_id'), 'WorldStockHolding', ['id'], unique=False)
    op.create_index(op.f('ix_WorldStockHolding_symbol'), 'WorldStockHolding', ['symbol'], unique=False)
    op.create_index(op.f('ix_WorldStockHolding_user_id'), 'WorldStockHolding', ['user_id'], unique=False)
    op.drop_index('idx_world_performance_account_id', table_name='WorldStockPerformance')
    op.drop_index('idx_world_performance_user_id', table_name='WorldStockPerformance')
    op.create_index(op.f('ix_WorldStockPerformance_account_id'), 'WorldStockPerformance', ['account_id'], unique=False)
    op.create_index(op.f('ix_WorldStockPerformance_id'), 'WorldStockPerformance', ['id'], unique=False)
    op.create_index(op.f('ix_WorldStockPerformance_user_id'), 'WorldStockPerformance', ['user_id'], unique=False)
    op.drop_index('idx_world_transaction_account_id', table_name='WorldStockTransaction')
    op.drop_index('idx_world_transaction_date', table_name='WorldStockTransaction')
    op.drop_index('idx_world_transaction_symbol', table_name='WorldStockTransaction')
    op.drop_index('idx_world_transaction_user_id', table_name='WorldStockTransaction')
    op.create_index(op.f('ix_WorldStockTransaction_account_id'), 'WorldStockTransaction', ['account_id'], unique=False)
    op.create_index(op.f('ix_WorldStockTransaction_id'), 'WorldStockTransaction', ['id'], unique=False)
    op.create_index(op.f('ix_WorldStockTransaction_symbol'), 'WorldStockTransaction', ['symbol'], unique=False)
    op.create_index(op.f('ix_WorldStockTransaction_transaction_date'), 'WorldStockTransaction', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_WorldStockTransaction_user_id'), 'WorldStockTransaction', ['user_id'], unique=False)
    op.add_column('users', sa.Column('role', sa.Enum('ADMIN', 'USER', 'VIEWER', name='userrole'), nullable=False, server_default='USER'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_index(op.f('ix_WorldStockTransaction_user_id'), table_name='WorldStockTransaction')
    op.drop_index(op.f('ix_WorldStockTransaction_transaction_date'), table_name='WorldStockTransaction')
    op.drop_index(op.f('ix_WorldStockTransaction_symbol'), table_name='WorldStockTransaction')
    op.drop_index(op.f('ix_WorldStockTransaction_id'), table_name='WorldStockTransaction')
    op.drop_index(op.f('ix_WorldStockTransaction_account_id'), table_name='WorldStockTransaction')
    op.create_index('idx_world_transaction_user_id', 'WorldStockTransaction', ['user_id'], unique=False)
    op.create_index('idx_world_transaction_symbol', 'WorldStockTransaction', ['symbol'], unique=False)
    op.create_index('idx_world_transaction_date', 'WorldStockTransaction', ['transaction_date'], unique=False)
    op.create_index('idx_world_transaction_account_id', 'WorldStockTransaction', ['account_id'], unique=False)
    op.drop_index(op.f('ix_WorldStockPerformance_user_id'), table_name='WorldStockPerformance')
    op.drop_index(op.f('ix_WorldStockPerformance_id'), table_name='WorldStockPerformance')
    op.drop_index(op.f('ix_WorldStockPerformance_account_id'), table_name='WorldStockPerformance')
    op.create_index('idx_world_performance_user_id', 'WorldStockPerformance', ['user_id'], unique=False)
    op.create_index('idx_world_performance_account_id', 'WorldStockPerformance', ['account_id'], unique=False)
    op.drop_index(op.f('ix_WorldStockHolding_user_id'), table_name='WorldStockHolding')
    op.drop_index(op.f('ix_WorldStockHolding_symbol'), table_name='WorldStockHolding')
    op.drop_index(op.f('ix_WorldStockHolding_id'), table_name='WorldStockHolding')
    op.drop_index(op.f('ix_WorldStockHolding_account_id'), table_name='WorldStockHolding')
    op.create_index('idx_world_holding_user_id', 'WorldStockHolding', ['user_id'], unique=False)
    op.create_index('idx_world_holding_symbol', 'WorldStockHolding', ['symbol'], unique=False)
    op.create_index('idx_world_holding_account_id', 'WorldStockHolding', ['account_id'], unique=False)
    op.drop_index(op.f('ix_WorldStockDividend_user_id'), table_name='WorldStockDividend')
    op.drop_index(op.f('ix_WorldStockDividend_symbol'), table_name='WorldStockDividend')
    op.drop_index(op.f('ix_WorldStockDividend_payment_date'), table_name='WorldStockDividend')
    op.drop_index(op.f('ix_WorldStockDividend_id'), table_name='WorldStockDividend')
    op.drop_index(op.f('ix_WorldStockDividend_account_id'), table_name='WorldStockDividend')
    op.create_index('idx_world_dividend_user_id', 'WorldStockDividend', ['user_id'], unique=False)
    op.create_index('idx_world_dividend_symbol', 'WorldStockDividend', ['symbol'], unique=False)
    op.create_index('idx_world_dividend_date', 'WorldStockDividend', ['payment_date'], unique=False)
    op.create_index('idx_world_dividend_account_id', 'WorldStockDividend', ['account_id'], unique=False)
    op.drop_index(op.f('ix_WorldStockAccount_user_id'), table_name='WorldStockAccount')
    op.drop_index(op.f('ix_WorldStockAccount_id'), table_name='WorldStockAccount')
    op.drop_index(op.f('ix_WorldStockAccount_account_number'), table_name='WorldStockAccount')
    op.create_index('idx_world_account_user_id', 'WorldStockAccount', ['user_id'], unique=False)
    op.create_index('idx_world_account_number', 'WorldStockAccount', ['account_number'], unique=False)
    op.create_unique_constraint('WorldStockAccount_account_number_key', 'WorldStockAccount', ['account_number'])
    # ### end Alembic commands ###
