"""add_theme_to_users

Revision ID: 9fa14511a323
Revises: e9f0a1b2c3d4
Create Date: 2026-04-08 20:51:47.351935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9fa14511a323'
down_revision = 'e9f0a1b2c3d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stock_prices_market', table_name='stock_prices')
    op.drop_index('idx_stock_prices_ticker', table_name='stock_prices')
    op.drop_index('idx_stock_prices_updated', table_name='stock_prices')
    op.drop_table('stock_prices')
    op.alter_column('calendar_events', 'event_type',
               existing_type=postgresql.ENUM('MARKET_CLOSED', 'EARLY_CLOSE', 'EARNINGS', 'ECONOMIC_DATA', 'FOMC', 'HOLIDAY', name='event_type'),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.alter_column('calendar_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('calendar_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_calendar_events_id'), 'calendar_events', ['id'], unique=False)
    op.drop_index('ix_EducationProgress_user_id', table_name='education_progress')
    op.create_index(op.f('ix_education_progress_user_id'), 'education_progress', ['user_id'], unique=False)
    op.alter_column('exchange_rates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_exchange_rate_unique', table_name='exchange_rates')
    op.create_unique_constraint('idx_exchange_rate_unique', 'exchange_rates', ['from_currency', 'to_currency', 'date'])
    op.create_index(op.f('ix_exchange_rates_id'), 'exchange_rates', ['id'], unique=False)
    op.drop_index('ix_IsraeliDividend_id', table_name='israeli_dividends')
    op.drop_index('ix_IsraeliDividend_user_id', table_name='israeli_dividends')
    op.create_index(op.f('ix_israeli_dividends_id'), 'israeli_dividends', ['id'], unique=False)
    op.create_index(op.f('ix_israeli_dividends_user_id'), 'israeli_dividends', ['user_id'], unique=False)
    op.drop_index('ix_IsraeliReportUpload_id', table_name='israeli_report_uploads')
    op.drop_index('ix_IsraeliReportUpload_upload_batch_id', table_name='israeli_report_uploads')
    op.drop_index('ix_IsraeliReportUpload_user_id', table_name='israeli_report_uploads')
    op.create_index(op.f('ix_israeli_report_uploads_id'), 'israeli_report_uploads', ['id'], unique=False)
    op.create_index(op.f('ix_israeli_report_uploads_upload_batch_id'), 'israeli_report_uploads', ['upload_batch_id'], unique=False)
    op.create_index(op.f('ix_israeli_report_uploads_user_id'), 'israeli_report_uploads', ['user_id'], unique=False)
    op.drop_index('ix_IsraeliStockHolding_id', table_name='israeli_stock_holdings')
    op.drop_index('ix_IsraeliStockHolding_user_id', table_name='israeli_stock_holdings')
    op.create_index(op.f('ix_israeli_stock_holdings_id'), 'israeli_stock_holdings', ['id'], unique=False)
    op.create_index(op.f('ix_israeli_stock_holdings_user_id'), 'israeli_stock_holdings', ['user_id'], unique=False)
    op.drop_index('ix_IsraeliStockTransaction_id', table_name='israeli_stock_transactions')
    op.drop_index('ix_IsraeliStockTransaction_user_id', table_name='israeli_stock_transactions')
    op.create_index(op.f('ix_israeli_stock_transactions_id'), 'israeli_stock_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_israeli_stock_transactions_user_id'), 'israeli_stock_transactions', ['user_id'], unique=False)
    op.drop_index('ix_IsraeliStocks_id', table_name='israeli_stocks')
    op.drop_index('ix_IsraeliStocks_security_no', table_name='israeli_stocks')
    op.drop_index('ix_IsraeliStocks_symbol', table_name='israeli_stocks')
    op.drop_index('ix_israelistocks_yfinance_ticker', table_name='israeli_stocks')
    op.create_index(op.f('ix_israeli_stocks_id'), 'israeli_stocks', ['id'], unique=False)
    op.create_index(op.f('ix_israeli_stocks_security_no'), 'israeli_stocks', ['security_no'], unique=True)
    op.create_index(op.f('ix_israeli_stocks_symbol'), 'israeli_stocks', ['symbol'], unique=False)
    op.create_index(op.f('ix_israeli_stocks_yfinance_ticker'), 'israeli_stocks', ['yfinance_ticker'], unique=False)
    op.drop_index('ix_PendingIsraeliTransaction_id', table_name='pending_israeli_transactions')
    op.drop_index('ix_PendingIsraeliTransaction_upload_batch_id', table_name='pending_israeli_transactions')
    op.drop_index('ix_PendingIsraeliTransaction_user_id', table_name='pending_israeli_transactions')
    op.create_index(op.f('ix_pending_israeli_transactions_id'), 'pending_israeli_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_pending_israeli_transactions_upload_batch_id'), 'pending_israeli_transactions', ['upload_batch_id'], unique=False)
    op.create_index(op.f('ix_pending_israeli_transactions_user_id'), 'pending_israeli_transactions', ['user_id'], unique=False)
    op.alter_column('pending_world_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_pending_world_transactions_id'), 'pending_world_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_pending_world_transactions_upload_batch_id'), 'pending_world_transactions', ['upload_batch_id'], unique=False)
    op.create_index(op.f('ix_pending_world_transactions_user_id'), 'pending_world_transactions', ['user_id'], unique=False)
    op.alter_column('user_event_notification_preferences', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_event_notification_preferences', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_user_event_prefs_user_id', table_name='user_event_notification_preferences')
    op.create_index(op.f('ix_user_event_notification_preferences_id'), 'user_event_notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_event_notification_preferences_user_id'), 'user_event_notification_preferences', ['user_id'], unique=True)
    op.add_column('users', sa.Column('theme', sa.String(length=50), nullable=True))
    op.alter_column('world_dividends', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_world_dividends_id'), 'world_dividends', ['id'], unique=False)
    op.create_index(op.f('ix_world_dividends_user_id'), 'world_dividends', ['user_id'], unique=False)
    op.alter_column('world_stock_holdings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('world_stock_holdings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_world_holding_unique', table_name='world_stock_holdings')
    op.create_unique_constraint('idx_world_holding_unique', 'world_stock_holdings', ['user_id', 'ticker', 'source_pdf'])
    op.create_index(op.f('ix_world_stock_holdings_id'), 'world_stock_holdings', ['id'], unique=False)
    op.create_index(op.f('ix_world_stock_holdings_user_id'), 'world_stock_holdings', ['user_id'], unique=False)
    op.alter_column('world_stock_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_world_stock_transactions_id'), 'world_stock_transactions', ['id'], unique=False)
    op.create_index(op.f('ix_world_stock_transactions_user_id'), 'world_stock_transactions', ['user_id'], unique=False)
    op.drop_column('world_stock_transactions', 'realized_pl')
    op.drop_column('world_stock_transactions', 'cost_basis')
    op.alter_column('world_stocks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('world_stocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_world_stock_ticker_exchange', table_name='world_stocks')
    op.create_unique_constraint('idx_world_stock_ticker_exchange', 'world_stocks', ['ticker', 'exchange'])
    op.create_index(op.f('ix_world_stocks_exchange'), 'world_stocks', ['exchange'], unique=False)
    op.create_index(op.f('ix_world_stocks_id'), 'world_stocks', ['id'], unique=False)
    op.create_index(op.f('ix_world_stocks_ticker'), 'world_stocks', ['ticker'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_world_stocks_ticker'), table_name='world_stocks')
    op.drop_index(op.f('ix_world_stocks_id'), table_name='world_stocks')
    op.drop_index(op.f('ix_world_stocks_exchange'), table_name='world_stocks')
    op.drop_constraint('idx_world_stock_ticker_exchange', 'world_stocks', type_='unique')
    op.create_index('idx_world_stock_ticker_exchange', 'world_stocks', ['ticker', 'exchange'], unique=False)
    op.alter_column('world_stocks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('world_stocks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('world_stock_transactions', sa.Column('cost_basis', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True))
    op.add_column('world_stock_transactions', sa.Column('realized_pl', sa.NUMERIC(precision=15, scale=4), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_world_stock_transactions_user_id'), table_name='world_stock_transactions')
    op.drop_index(op.f('ix_world_stock_transactions_id'), table_name='world_stock_transactions')
    op.alter_column('world_stock_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_world_stock_holdings_user_id'), table_name='world_stock_holdings')
    op.drop_index(op.f('ix_world_stock_holdings_id'), table_name='world_stock_holdings')
    op.drop_constraint('idx_world_holding_unique', 'world_stock_holdings', type_='unique')
    op.create_index('idx_world_holding_unique', 'world_stock_holdings', ['user_id', 'ticker', 'source_pdf'], unique=False)
    op.alter_column('world_stock_holdings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('world_stock_holdings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_world_dividends_user_id'), table_name='world_dividends')
    op.drop_index(op.f('ix_world_dividends_id'), table_name='world_dividends')
    op.alter_column('world_dividends', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'theme')
    op.drop_index(op.f('ix_user_event_notification_preferences_user_id'), table_name='user_event_notification_preferences')
    op.drop_index(op.f('ix_user_event_notification_preferences_id'), table_name='user_event_notification_preferences')
    op.create_index('ix_user_event_prefs_user_id', 'user_event_notification_preferences', ['user_id'], unique=False)
    op.alter_column('user_event_notification_preferences', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('user_event_notification_preferences', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_pending_world_transactions_user_id'), table_name='pending_world_transactions')
    op.drop_index(op.f('ix_pending_world_transactions_upload_batch_id'), table_name='pending_world_transactions')
    op.drop_index(op.f('ix_pending_world_transactions_id'), table_name='pending_world_transactions')
    op.alter_column('pending_world_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_pending_israeli_transactions_user_id'), table_name='pending_israeli_transactions')
    op.drop_index(op.f('ix_pending_israeli_transactions_upload_batch_id'), table_name='pending_israeli_transactions')
    op.drop_index(op.f('ix_pending_israeli_transactions_id'), table_name='pending_israeli_transactions')
    op.create_index('ix_PendingIsraeliTransaction_user_id', 'pending_israeli_transactions', ['user_id'], unique=False)
    op.create_index('ix_PendingIsraeliTransaction_upload_batch_id', 'pending_israeli_transactions', ['upload_batch_id'], unique=False)
    op.create_index('ix_PendingIsraeliTransaction_id', 'pending_israeli_transactions', ['id'], unique=False)
    op.drop_index(op.f('ix_israeli_stocks_yfinance_ticker'), table_name='israeli_stocks')
    op.drop_index(op.f('ix_israeli_stocks_symbol'), table_name='israeli_stocks')
    op.drop_index(op.f('ix_israeli_stocks_security_no'), table_name='israeli_stocks')
    op.drop_index(op.f('ix_israeli_stocks_id'), table_name='israeli_stocks')
    op.create_index('ix_israelistocks_yfinance_ticker', 'israeli_stocks', ['yfinance_ticker'], unique=False)
    op.create_index('ix_IsraeliStocks_symbol', 'israeli_stocks', ['symbol'], unique=False)
    op.create_index('ix_IsraeliStocks_security_no', 'israeli_stocks', ['security_no'], unique=False)
    op.create_index('ix_IsraeliStocks_id', 'israeli_stocks', ['id'], unique=False)
    op.drop_index(op.f('ix_israeli_stock_transactions_user_id'), table_name='israeli_stock_transactions')
    op.drop_index(op.f('ix_israeli_stock_transactions_id'), table_name='israeli_stock_transactions')
    op.create_index('ix_IsraeliStockTransaction_user_id', 'israeli_stock_transactions', ['user_id'], unique=False)
    op.create_index('ix_IsraeliStockTransaction_id', 'israeli_stock_transactions', ['id'], unique=False)
    op.drop_index(op.f('ix_israeli_stock_holdings_user_id'), table_name='israeli_stock_holdings')
    op.drop_index(op.f('ix_israeli_stock_holdings_id'), table_name='israeli_stock_holdings')
    op.create_index('ix_IsraeliStockHolding_user_id', 'israeli_stock_holdings', ['user_id'], unique=False)
    op.create_index('ix_IsraeliStockHolding_id', 'israeli_stock_holdings', ['id'], unique=False)
    op.drop_index(op.f('ix_israeli_report_uploads_user_id'), table_name='israeli_report_uploads')
    op.drop_index(op.f('ix_israeli_report_uploads_upload_batch_id'), table_name='israeli_report_uploads')
    op.drop_index(op.f('ix_israeli_report_uploads_id'), table_name='israeli_report_uploads')
    op.create_index('ix_IsraeliReportUpload_user_id', 'israeli_report_uploads', ['user_id'], unique=False)
    op.create_index('ix_IsraeliReportUpload_upload_batch_id', 'israeli_report_uploads', ['upload_batch_id'], unique=False)
    op.create_index('ix_IsraeliReportUpload_id', 'israeli_report_uploads', ['id'], unique=False)
    op.drop_index(op.f('ix_israeli_dividends_user_id'), table_name='israeli_dividends')
    op.drop_index(op.f('ix_israeli_dividends_id'), table_name='israeli_dividends')
    op.create_index('ix_IsraeliDividend_user_id', 'israeli_dividends', ['user_id'], unique=False)
    op.create_index('ix_IsraeliDividend_id', 'israeli_dividends', ['id'], unique=False)
    op.drop_index(op.f('ix_exchange_rates_id'), table_name='exchange_rates')
    op.drop_constraint('idx_exchange_rate_unique', 'exchange_rates', type_='unique')
    op.create_index('idx_exchange_rate_unique', 'exchange_rates', ['from_currency', 'to_currency', 'date'], unique=False)
    op.alter_column('exchange_rates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_education_progress_user_id'), table_name='education_progress')
    op.create_index('ix_EducationProgress_user_id', 'education_progress', ['user_id'], unique=False)
    op.drop_index(op.f('ix_calendar_events_id'), table_name='calendar_events')
    op.alter_column('calendar_events', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('calendar_events', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('calendar_events', 'event_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('MARKET_CLOSED', 'EARLY_CLOSE', 'EARNINGS', 'ECONOMIC_DATA', 'FOMC', 'HOLIDAY', name='event_type'),
               existing_nullable=False)
    op.create_table('stock_prices',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"StockPrices_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('ticker', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('market', sa.VARCHAR(length=20), server_default=sa.text("'world'::character varying"), autoincrement=False, nullable=False),
    sa.Column('current_price', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('previous_close', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('price_change', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('price_change_pct', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True),
    sa.Column('day_high', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('day_low', sa.NUMERIC(precision=18, scale=4), autoincrement=False, nullable=True),
    sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('market_cap', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='StockPrices_pkey'),
    sa.UniqueConstraint('ticker', 'market', name='StockPrices_ticker_market_key')
    )
    op.create_index('idx_stock_prices_updated', 'stock_prices', ['updated_at'], unique=False)
    op.create_index('idx_stock_prices_ticker', 'stock_prices', ['ticker'], unique=False)
    op.create_index('idx_stock_prices_market', 'stock_prices', ['market'], unique=False)
    # ### end Alembic commands ###
